---
- hosts: all
  name: configure elasticsearch yum repo

  tasks:
  - name: download and install elasticsearch GPG key
    rpm_key:
      state=present
      key=https://artifacts.elastic.co/GPG-KEY-elasticsearch

  - name: create repo for elasticsearch 5.x packages
    yum_repository:
      name: elasticsearch
      description: Elasticsearch repository for 5.x packages
      baseurl: https://artifacts.elastic.co/packages/5.x/yum
      gpgcheck: yes
