---
- hosts: kibana
  name: install and configure kibana
  any_errors_fatal: true

  tasks:
  - name: install kibana
    yum:
      name: kibana
      state: present

  - name: set kibana server address
    lineinfile:
      dest: /etc/kibana/kibana.yml
      regexp: #server.name
      insertafter: "^#server.host"
      line: "server.host: \"{{ ansible_default_ipv4.address }}\""

  - name: set elasticsearch node address
    lineinfile:
      dest: /etc/kibana/kibana.yml
      regexp: #elasticsearch.url
      insertafter: "^#elasticsearch.url"
      line: "elasticsearch.url: \"http://{{ ansible_default_ipv4.address }}:9200\""

  - name: start kibana service
    systemd:
      name: kibana
      state: started
      enabled: yes
      daemon_reload: yes
